{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "billing-service.fullname" . }}-limits
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
spec:
  limits:
  {{- toYaml .Values.limitRange.limits | nindent 2 }}
{{- end }}
