{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: billing-redis
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "billing-service.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
  selector:
    {{- include "billing-service.redis.selectorLabels" . | nindent 4 }}
{{- end }}
