{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gateway-service.fullname" . }}-pdb
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "gateway-service.selectorLabels" . | nindent 6 }}
{{- end }}
