{{- if and .Values.redis.enabled .Values.redis.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-redis-netpol
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "gateway-service.redis.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gateway-service.redis.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- toYaml .Values.redis.networkPolicy.ingress | nindent 2 }}
  egress:
  - to: []
    ports:
    - protocol: UDP
      port: 53
{{- end }}
