{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-service.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secrets.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
