apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foundation-iam-service.fullname" . }}-secrets
  labels:
    {{- include "foundation-iam-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  database-password: {{ .Values.infraServices.postgresql.password | b64enc | quote }}

  # RabbitMQ credentials
  rabbitmq-password: {{ .Values.infraServices.rabbitmq.password | b64enc | quote }}

  # Redis credentials
  redis-password: {{ .Values.infraServices.redis.password | b64enc | quote }}

  # Object Storage / MinIO credentials
  s3-access-key: {{ .Values.infraServices.objectstorage.accessKey | b64enc | quote }}
  s3-secret-key: {{ .Values.infraServices.objectstorage.secretKey | b64enc | quote }}

  # Mail credentials
  mail-username: {{ .Values.config.mail.username | b64enc | quote }}
  mail-password: {{ .Values.config.mail.password | b64enc | quote }}

  # OAuth2 / OIDC secrets
  oidc-encryption-key: {{ .Values.config.oauth2.encryptionKey | b64enc | quote }}
  oauth2-google-client-secret: {{ .Values.config.oauth2.providers.google.clientSecret | b64enc | quote }}
  oauth2-github-client-secret: {{ .Values.config.oauth2.providers.github.clientSecret | b64enc | quote }}
  oauth2-microsoft-client-secret: {{ .Values.config.oauth2.providers.microsoft.clientSecret | b64enc | quote }}
