server:
  port: 8081

spring:
  application:
    name: gripday-auth-service
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized