apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foundation-billing-service.fullname" . }}-secrets
  labels:
    {{- include "foundation-billing-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  database-password: {{ .Values.infraServices.postgresql.password | b64enc | quote }}

  # RabbitMQ credentials
  rabbitmq-password: {{ .Values.infraServices.rabbitmq.password | b64enc | quote }}

  # Mail credentials
  mail-username: {{ .Values.config.mail.username | b64enc | quote }}
  mail-password: {{ .Values.config.mail.password | b64enc | quote }}

  # Stripe credentials
  stripe-secret-key: {{ .Values.config.stripe.secretKey | default "" | b64enc | quote }}
  stripe-webhook-secret: {{ .Values.config.stripe.webhookSecret | default "" | b64enc | quote }}
