apiVersion: v1
kind: Namespace
metadata:
  name: gripday-auth
  labels:
    app.kubernetes.io/name: gripday-auth-service
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: gripday-platform
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging-env
  labels:
    app.kubernetes.io/part-of: gripday-platform
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: production-env
  labels:
    app.kubernetes.io/part-of: gripday-platform
    environment: production