apiVersion: v2
name: user-service
description: A Helm chart for IQ Scaffold User Service
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - authentication
  - microservices
  - iqscaffold
maintainers:
  - name: IQ Scaffold Platform Team
home: https://iqscaffold.site
sources:
  - https://github.com/iqscaffold/iqscaffold-user-service
dependencies: []
