{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: bookstore-postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "bookstore-service.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
  - port: {{ .Values.postgresql.service.port }}
    targetPort: {{ .Values.postgresql.service.port }}
    protocol: TCP
    name: postgres
  selector:
    {{- include "bookstore-service.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
