{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "bookstore-service.fullname" . }}-quota
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "bookstore-service.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
{{- end }}
