apiVersion: v2
name: foundation-audit-service
description: Centralized audit logging service for iQ Key Value Platform.
version: 0.3.0
appVersion: "0.3.0"

keywords:
  - iqkv
  - audit-service
  - multi-tenant
  - spring-boot
  - microservices
  - security
  - mybatis
  - audit-logging

home: https://github.com/IQKV/foundation-audit-service
sources:
  - https://github.com/IQKV/foundation-audit-service

maintainers:
  - name: iQ Key Value Team
    email: team@iqkv.dev
