spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/billing_db
    username: ${DB_USERNAME:billing_user}
    password: ${DB_PASSWORD:billing_pass}
    hikari:
      pool-name: BillingServiceHikariPool-Local
      leak-detection-threshold: 60000

  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

iqscaffold:
  billing:
    payment:
      stripe:
        api-key: ${STRIPE_API_KEY:sk_test_dummy}
        webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_dummy}
        client-id: ${STRIPE_CLIENT_ID:ca_test_dummy}
