apiVersion: v2
name: foundation-infra
description: IQ Key Value Platform Core Infrastructure Services Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - iqkv
  - infrastructure
  - microservices
  - postgresql
  - redis
  - rabbitmq
home: https://github.com/IQKV/microservices-platform
sources:
  - https://github.com/IQKV/microservices-platform
maintainers:
  - name: IQ Key Value Team
    email: team@iqkv.com
