apiVersion: v2
name: foundation-infra
description: iQ Key Value Platform Core Infrastructure Services Helm Chart
type: application
version: 0.3.0
appVersion: "0.3.0"
keywords:
  - iqkv
  - infrastructure
  - microservices
  - postgresql
  - redis
  - rabbitmq
home: https://github.com/IQKV/microservices-platform
sources:
  - https://github.com/IQKV/microservices-platform
maintainers:
  - name: iQ Key Value Team
    email: team@iqkv.com
