apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "standard-ui-blank-astro-daisyui-ssr.fullname" . }}-config
  labels:
    {{- include "standard-ui-blank-astro-daisyui-ssr.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.app.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
