apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foundation-microservice-project-layout.fullname" . }}-secrets
  labels:
    {{- include "foundation-microservice-project-layout.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  database-password: {{ .Values.infraServices.postgresql.password | b64enc | quote }}

  # RabbitMQ credentials
  rabbitmq-password: {{ .Values.infraServices.rabbitmq.password | b64enc | quote }}
