apiVersion: v1
kind: Namespace
metadata:
  name: iqscaffold-bookstore
  labels:
    app.kubernetes.io/name: iqscaffold-bookstore-service
    app.kubernetes.io/component: bookstore
    app.kubernetes.io/part-of: iqscaffold
    environment: local
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging-env
  labels:
    app.kubernetes.io/part-of: iqscaffold
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: iqscaffold-production-env
  labels:
    app.kubernetes.io/part-of: iqscaffold
    environment: production
